[package]
name = "drawdown"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8"
rand_distr = "0.4"
matlib = { path = "../src/core/matlib" }

[[bin]]
name = "drawdown"
path = "src/main.rs"
