[package]
name = "indicators"
version = "0.1.0"
edition = "2024"

[lib]
name = "indicators"
path = "lib.rs"

[dependencies]
rand = "0.8"
matlib = { path = "../core/matlib" }
finance_tools = { path = "../finance_tools" }