[package]
name = "gap_analysis"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "gap_analysis"
path = "main.rs"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
matlib = { path = "../matlib" }
stats = { path = "../stats" }
finance_tools = { path = "../finance_tools" }